.TH PACEDUMP 1 "05 April 1998" "DICOM PS3" "pace dump"
.SH NAME
pacedump \- ACR/NEMA DICOM PS3 ... GE PACE dump contents
.SH SYNOPSIS
.HP 10
.B pacedump
.I inputfilename
.SH DESCRIPTION
.LP
.B pacedump
reads the named GE PACE input file and dumps its contents.
.LP
.SH OPTIONS
The dump output goes to standard error.
.PP
The basic switches are described in dcintro(1).
.SH ENVIRONMENT
.LP
\ 
.SH EXAMPLES
.LP
.RE
\ 
.RE
% pacedump test
.RE
\ 
.RE
[block:offset] Description        <value>
.RE
\ 
.RE
 ...
.SH FILES
.LP
\ 
.SH SEE ALSO
.BR dcintro(1) ,
.BR pacetodc(1)
.SH AUTHOR
Copyright (C) 1993-2010. David A. Clunie DBA PixelMed Publishing. All rights reserved.
.SH BUGS
