(0009,0004) VERS="CMT"	VR="IS"   VM="1"	Owner="Camtronics image level data"		Keyword="?"				Name="?"
(0009,0006) VERS="CMT"	VR="IS"   VM="1"	Owner="Camtronics image level data"		Keyword="?"				Name="?"
(0009,0009) VERS="CMT"	VR="LO"   VM="1"	Owner="Camtronics image level data"		Keyword="?"				Name="?"
(0009,0016) VERS="CMT"	VR="AE"   VM="1"	Owner="Camtronics image level data"		Keyword="?"				Name="?"
(0009,0017) VERS="CMT"	VR="CS"   VM="1"	Owner="Camtronics image level data"		Keyword="?"				Name="?"
(0009,0018) VERS="CMT"	VR="IS"   VM="1"	Owner="Camtronics image level data"		Keyword="?"				Name="?"

(0009,0000) VERS="CMT"	VR="CS"   VM="1"	Owner="QCA Results"		Keyword="AnalysisType"										Name="Analysis Type"
(0009,0004) VERS="CMT"	VR="LO"   VM="1"	Owner="QCA Results"		Keyword="SegmentName"										Name="Segment Name"
(0009,0012) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PreProcedureCatheterSize"							Name="Pre-procedure Catheter Size"
(0009,0013) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PreProcedureReferenceDiameter"						Name="Pre-procedure Reference Diameter"
(0009,0014) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PreProcedureMinimumLumenDiameter"					Name="Pre-procedure Minimum Lumen Diameter"
(0009,0015) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PreProcedureAverageDiameter"						Name="Pre-procedure Average Diameter"
(0009,0016) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PreProcedureStenosisLength"						Name="Pre-procedure Stenosis Length"
(0009,0017) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PreProcedureStenosisPercentage"					Name="Pre-procedure Stenosis %"
(0009,0018) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PreProcedureGeometricAreaReductionPercentage"		Name="Pre-procedure Geometric Area Reduction %"
(0009,0022) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PostProcedureCatheterSize"							Name="Post-procedure Catheter Size"
(0009,0023) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PostProcedureReferenceDiameter"					Name="Post-procedure Reference Diameter"
(0009,0024) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PostProcedureMinimumLumenDiameter"					Name="Post-procedure Minimum Lumen Diameter"
(0009,0025) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PostProcedureAverageDiameter"						Name="Post-procedure Average Diameter"
(0009,0026) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PostProcedureStenosisLength"						Name="Post-procedure Stenosis Length"
(0009,0027) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PostProcedureStenosisPercentage"					Name="Post-procedure Stenosis %"
(0009,0028) VERS="CMT"	VR="DS"   VM="1"	Owner="QCA Results"		Keyword="PostProcedureGeometricAreaReductionPercentage"		Name="Post-procedure Geometric Area Reduction %"

(0029,0010) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0010) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS"		Keyword="Commentline"			Name="Commentline"
(0029,0020) VERS="CMT"	VR="DS"   VM="1"	Owner="CAMTRONICS"		Keyword="EdgeEnhancementCoefficient"	Name="Edge Enhancement Coefficient"
(0029,0020) VERS="CMT"	VR="UN"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0030) VERS="CMT"	VR="UN"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0040) VERS="CMT"	VR="UN"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0050) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS"		Keyword="SceneText"			Name="Scene Text"
(0029,0060) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS"		Keyword="ImageText"			Name="Image Text"
(0029,0070) VERS="CMT"	VR="IS"   VM="1"	Owner="CAMTRONICS"		Keyword="PixelShiftHorizontal"		Name="Pixel Shift Horizontal"
(0029,0080) VERS="CMT"	VR="IS"   VM="1"	Owner="CAMTRONICS"		Keyword="PixelShiftVertical"		Name="Pixel Shift Vertical"
(0029,0090) VERS="CMT"	VR="IS"   VM="1"	Owner="CAMTRONICS"		Keyword="?"				Name="?"

