(0014,0023) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="CADFileFormat"										Name="CAD File Format"
(0014,0024) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="ComponentReferenceSystem"							Name="Component Reference System"
(0014,0025) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="ComponentManufacturingProcedure"					Name="Component Manufacturing Procedure"
(0014,0028) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="ComponentManufacturer"								Name="Component Manufacturer"
(0014,0030) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="MaterialThickness"									Name="Material Thickness"
(0014,0032) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="MaterialPipeDiameter"								Name="Material Pipe Diameter"
(0014,0034) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="MaterialIsolationDiameter"							Name="Material Isolation Diameter"
(0014,0042) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="MaterialGrade"										Name="Material Grade"
(0014,0044) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="MaterialPropertiesDescription"						Name="Material Properties Description"
(0014,0045) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="MaterialPropertiesFileFormatRetired"				Name="Material Properties File Format (Retired)"
(0014,0046) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="MaterialNotes"										Name="Material Notes"
(0014,0050) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ComponentShape"									Name="Component Shape"
(0014,0052) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CurvatureType"										Name="Curvature Type"
(0014,0054) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="OuterDiameter"										Name="Outer Diameter"
(0014,0056) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="InnerDiameter"										Name="Inner Diameter"
(0014,1010) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="ActualEnvironmentalConditions"						Name="Actual Environmental Conditions"
(0014,1020) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ExpiryDate"										Name="Expiry Date"
(0014,1040) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="EnvironmentalConditions"							Name="Environmental Conditions"
(0014,2002) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="EvaluatorSequence"									Name="Evaluator Sequence"
(0014,2004) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="EvaluatorNumber"									Name="Evaluator Number"
(0014,2006) VERS="DICONDE"	VR="PN"   VM="1"	Keyword="EvaluatorName"										Name="Evaluator Name"
(0014,2008) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="EvaluationAttempt"									Name="Evaluation Attempt"
(0014,2012) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="IndicationSequence"								Name="Indication Sequence"
(0014,2014) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="IndicationNumber"									Name="Indication Number "
(0014,2016) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="IndicationLabel"									Name="Indication Label"
(0014,2018) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="IndicationDescription"								Name="Indication Description"
(0014,201A) VERS="DICONDE"	VR="CS"   VM="1-n"	Keyword="IndicationType"									Name="Indication Type"
(0014,201C) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="IndicationDisposition"								Name="Indication Disposition"
(0014,201E) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="IndicationROISequence"								Name="Indication ROI Sequence"
(0014,2030) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="IndicationPhysicalPropertySequence"				Name="Indication Physical Property Sequence"
(0014,2032) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="PropertyLabel"										Name="Property Label"
(0014,2202) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="CoordinateSystemNumberOfAxes"						Name="Coordinate System Number of Axes "
(0014,2204) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="CoordinateSystemAxesSequence"						Name="Coordinate System Axes Sequence"
(0014,2206) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CoordinateSystemAxisDescription"					Name="Coordinate System Axis Description"
(0014,2208) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CoordinateSystemDataSetMapping"					Name="Coordinate System Data Set Mapping"
(0014,220A) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="CoordinateSystemAxisNumber"						Name="Coordinate System Axis Number"
(0014,220C) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CoordinateSystemAxisType"							Name="Coordinate System Axis Type"
(0014,220E) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CoordinateSystemAxisUnits"							Name="Coordinate System Axis Units"
(0014,2210) VERS="DICONDE"	VR="OB"   VM="1"	Keyword="CoordinateSystemAxisValues"						Name="Coordinate System Axis Values"
(0014,2220) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="CoordinateSystemTransformSequence"					Name="Coordinate System Transform Sequence"
(0014,2222) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="TransformDescription"								Name="Transform Description"
(0014,2224) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="TransformNumberOfAxes"								Name="Transform Number of Axes"
(0014,2226) VERS="DICONDE"	VR="IS"   VM="1-n"	Keyword="TransformOrderOfAxes"								Name="Transform Order of Axes"
(0014,2228) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="TransformedAxisUnits"								Name="Transformed Axis Units"
(0014,222A) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="CoordinateSystemTransformRotationAndScaleMatrix"	Name="Coordinate System Transform Rotation and Scale Matrix"
(0014,222C) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="CoordinateSystemTransformTranslationMatrix"		Name="Coordinate System Transform Translation Matrix"
(0014,3011) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="InternalDetectorFrameTime"							Name="Internal Detector Frame Time"
(0014,3012) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfFramesIntegrated"							Name="Number of Frames Integrated"
(0014,3020) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DetectorTemperatureSequence"						Name="Detector Temperature Sequence"
(0014,3022) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SensorName"										Name="Sensor Name"
(0014,3024) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="HorizontalOffsetOfSensor"							Name="Horizontal Offset of Sensor"
(0014,3026) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VerticalOffsetOfSensor"							Name="Vertical Offset of Sensor"
(0014,3028) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SensorTemperature"									Name="Sensor Temperature"
(0014,3040) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DarkCurrentSequence"								Name="Dark Current Sequence"
(0014,3050) VERS="DICONDE"	VR="OW/OB" VM="1"	Keyword="DarkCurrentCounts"									Name="Dark Current Counts"
(0014,3060) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="GainCorrectionReferenceSequence"					Name="Gain Correction Reference Sequence"
(0014,3070) VERS="DICONDE"	VR="OW/OB" VM="1"	Keyword="AirCounts"											Name="Air Counts"
(0014,3071) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="KVUsedInGainCalibration"							Name="KV Used in Gain Calibration"
(0014,3072) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MAUsedInGainCalibration"							Name="MA Used in Gain Calibration"
(0014,3073) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfFramesUsedForIntegration"					Name="Number of Frames Used for Integration"
(0014,3074) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="FilterMaterialUsedInGainCalibration"				Name="Filter Material Used in Gain Calibration"
(0014,3075) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="FilterThicknessUsedInGainCalibration"				Name="Filter Thickness Used in Gain Calibration"
(0014,3076) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="DateOfGainCalibration"								Name="Date of Gain Calibration"
(0014,3077) VERS="DICONDE"	VR="TM"   VM="1"	Keyword="TimeOfGainCalibration"								Name="Time of Gain Calibration"
(0014,3080) VERS="DICONDE"	VR="OB"   VM="1"	Keyword="BadPixelImage"										Name="Bad Pixel Image"
(0014,3099) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="CalibrationNotes"									Name="Calibration Notes"
(0014,4002) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PulserEquipmentSequence"							Name="Pulser Equipment Sequence"
(0014,4004) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="PulserType"										Name="Pulser Type"
(0014,4006) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="PulserNotes"										Name="Pulser Notes"
(0014,4008) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiverEquipmentSequence"							Name="Receiver Equipment Sequence"
(0014,400A) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="AmplifierType"										Name="Amplifier Type"
(0014,400C) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="ReceiverNotes"										Name="Receiver Notes"
(0014,400E) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PreAmplifierEquipmentSequence"						Name="Pre-Amplifier Equipment Sequence"
(0014,400F) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="PreAmplifierNotes"									Name="Pre-Amplifier Notes"
(0014,4010) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="TransmitTransducerSequence"						Name="Transmit Transducer Sequence"
(0014,4011) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiveTransducerSequence"							Name="Receive Transducer Sequence"
(0014,4012) VERS="DICONDE"	VR="US"   VM="1"	Keyword="NumberOfElements"									Name="Number of Elements"
(0014,4013) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ElementShape"										Name="Element Shape"
(0014,4014) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementDimensionA"									Name="Element Dimension A"
(0014,4015) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementDimensionB"									Name="Element Dimension B"
(0014,4016) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementPitchA"										Name="Element Pitch A"
(0014,4017) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredBeamDimensionA"							Name="Measured Beam Dimension A"
(0014,4018) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredBeamDimensionB"							Name="Measured Beam Dimension B"
(0014,4019) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="LocationOfMeasuredBeamDiameter"					Name="Location of Measured Beam Diameter"
(0014,401A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NominalFrequency"									Name="Nominal Frequency"
(0014,401B) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredCenterFrequency"							Name="Measured Center Frequency"
(0014,401C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredBandwidth"									Name="Measured Bandwidth"
(0014,401D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementPitchB"										Name="Element Pitch B"
(0014,4020) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PulserSettingsSequence"							Name="Pulser Settings Sequence"
(0014,4022) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="PulseWidth"										Name="Pulse Width"
(0014,4024) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ExcitationFrequency"								Name="Excitation Frequency"
(0014,4026) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ModulationType"									Name="Modulation Type"
(0014,4028) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="Damping"											Name="Damping"
(0014,4030) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiverSettingsSequence"							Name="Receiver Settings Sequence"
(0014,4031) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="AcquiredSoundpathLength"							Name="Acquired Soundpath Length"
(0014,4032) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="AcquisitionCompressionType"						Name="Acquisition Compression Type"
(0014,4033) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="AcquisitionSampleSize"								Name="Acquisition Sample Size"
(0014,4034) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="RectifierSmoothing"								Name="Rectifier Smoothing"
(0014,4035) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DACSequence"										Name="DAC Sequence"
(0014,4036) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="DACType"											Name="DAC Type"
(0014,4038) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="DACGainPoints"										Name="DAC Gain Points"
(0014,403A) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="DACTimePoints"										Name="DAC Time Points"
(0014,403C) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="DACAmplitude"										Name="DAC Amplitude"
(0014,4040) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PreAmplifierSettingsSequence"						Name="Pre-Amplifier Settings Sequence"
(0014,4050) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="TransmitTransducerSettingsSequence"				Name="Transmit Transducer Settings Sequence"
(0014,4051) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiveTransducerSettingsSequence"					Name="Receive Transducer Settings Sequence"
(0014,4052) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="IncidentAngle"										Name="Incident Angle"
(0014,4054) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CouplingTechnique"									Name="Coupling Technique"
(0014,4056) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CouplingMedium"									Name="Coupling Medium"
(0014,4057) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="CouplingVelocity"									Name="Coupling Velocity"
(0014,4058) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeCenterLocationX"								Name="Probe Center Location X"
(0014,4059) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeCenterLocationZ"								Name="Probe Center Location Z"
(0014,405A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SoundPathLength"									Name="Sound Path Length"
(0014,405C) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="DelayLawIdentifier"								Name="Delay Law Identifier"
(0014,4060) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="GateSettingsSequence"								Name="Gate Settings Sequence"
(0014,4062) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="GateThreshold"										Name="Gate Threshold"
(0014,4064) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VelocityOfSound"									Name="Velocity of Sound"
(0014,4070) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="CalibrationSettingsSequence"						Name="Calibration Settings Sequence"
(0014,4072) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CalibrationProcedure"								Name="Calibration Procedure"
(0014,4074) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="ProcedureVersion"									Name="Procedure Version"
(0014,4076) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ProcedureCreationDate"								Name="Procedure Creation Date"
(0014,4078) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ProcedureExpirationDate"							Name="Procedure Expiration Date"
(0014,407A) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ProcedureLastModifiedDate"							Name="Procedure Last Modified Date"
(0014,407C) VERS="DICONDE"	VR="TM"   VM="1-n"	Keyword="CalibrationTime"									Name="Calibration Time"
(0014,407E) VERS="DICONDE"	VR="DA"   VM="1-n"	Keyword="CalibrationDate"									Name="Calibration Date"
(0014,4080) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ProbeDriveEquipmentSequence"						Name="Probe Drive Equipment Sequence"
(0014,4081) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="DriveType"											Name="Drive Type"
(0014,4082) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="ProbeDriveNotes"									Name="Probe Drive Notes"
(0014,4083) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DriveProbeSequence"								Name="Drive Probe Sequence"
(0014,4084) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeInductance"									Name="Probe Inductance"
(0014,4085) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeResistance"									Name="Probe Resistance"
(0014,4086) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiveProbeSequence"								Name="Receive Probe Sequence"
(0014,4087) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ProbeDriveSettingsSequence"						Name="Probe Drive Settings Sequence"
(0014,4088) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="BridgeResistors"									Name="Bridge Resistors"
(0014,408B) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="UserSelectedGainY"									Name="User Selected Gain Y"
(0014,408C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="UserSelectedPhase"									Name="User Selected Phase"
(0014,4091) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ChannelSettingsSequence"							Name="Channel Settings Sequence"
(0014,4092) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ChannelThreshold"									Name="Channel Threshold"
(0014,5002) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="LINACEnergy"										Name="LINAC Energy"
(0014,5004) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="LINACOutput"										Name="LINAC Output"


