(4010,0001) VERS="DICOS"	VR="CS"   VM="1"	Keyword="LowEnergyDetectors"					Name="Low Energy Detectors"
(4010,0002) VERS="DICOS"	VR="CS"   VM="1"	Keyword="HighEnergyDetectors"					Name="High Energy Detectors"
(4010,0004) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="DetectorGeometrySequence"				Name="Detector Geometry Sequence"
(4010,1001) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="ThreatROIVoxelSequence"				Name="Threat ROI Voxel Sequence"
(4010,1004) VERS="DICOS"	VR="FL"   VM="3"	Keyword="ThreatROIBase"							Name="Threat ROI Base"
(4010,1005) VERS="DICOS"	VR="FL"   VM="3"	Keyword="ThreatROIExtents"						Name="Threat ROI Extents"
(4010,1006) VERS="DICOS"	VR="OB"   VM="1"	Keyword="ThreatROIBitmap"						Name="Threat ROI Bitmap"
(4010,1007) VERS="DICOS"	VR="SH"   VM="1"	Keyword="RouteSegmentID"						Name="Route Segment ID"
(4010,1008) VERS="DICOS"	VR="CS"   VM="1"	Keyword="GantryType"							Name="Gantry Type"
(4010,1009) VERS="DICOS"	VR="CS"   VM="1"	Keyword="OOIOwnerType"							Name="OOI Owner Type"
(4010,100A) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="RouteSegmentSequence"					Name="Route Segment Sequence"
(4010,1010) VERS="DICOS"	VR="US"   VM="1"	Keyword="PotentialThreatObjectID"				Name="Potential Threat Object ID"
(4010,1011) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="ThreatSequence"						Name="Threat Sequence"
(4010,1012) VERS="DICOS"	VR="CS"   VM="1"	Keyword="ThreatCategory"						Name="Threat Category"
(4010,1013) VERS="DICOS"	VR="LT"   VM="1"	Keyword="ThreatCategoryDescription"				Name="Threat Category Description"
(4010,1014) VERS="DICOS"	VR="CS"   VM="1"	Keyword="ATDAbilityAssessment"					Name="ATD Ability Assessment"
(4010,1015) VERS="DICOS"	VR="CS"   VM="1"	Keyword="ATDAssessmentFlag"						Name="ATD Assessment Flag"
(4010,1016) VERS="DICOS"	VR="FL"   VM="1"	Keyword="ATDAssessmentProbability"				Name="ATD Assessment Probability"
(4010,1017) VERS="DICOS"	VR="FL"   VM="1"	Keyword="Mass"									Name="Mass"
(4010,1018) VERS="DICOS"	VR="FL"   VM="1"	Keyword="Density"								Name="Density"
(4010,1019) VERS="DICOS"	VR="FL"   VM="1"	Keyword="ZEffective"							Name="Z Effective"
(4010,101A) VERS="DICOS"	VR="SH"   VM="1"	Keyword="BoardingPassID"						Name="Boarding Pass ID"
(4010,101B) VERS="DICOS"	VR="FL"   VM="3"	Keyword="CenterOfMass"							Name="Center of Mass"
(4010,101C) VERS="DICOS"	VR="FL"   VM="3"	Keyword="CenterOfPTO"							Name="Center of PTO"
(4010,101D) VERS="DICOS"	VR="FL"   VM="6-n"	Keyword="BoundingPolygon"						Name="Bounding Polygon"
(4010,101E) VERS="DICOS"	VR="SH"   VM="1"	Keyword="RouteSegmentStartLocationID"			Name="Route Segment Start Location ID"
(4010,101F) VERS="DICOS"	VR="SH"   VM="1"	Keyword="RouteSegmentEndLocationID"				Name="Route Segment End Location ID"
(4010,1020) VERS="DICOS"	VR="CS"   VM="1"	Keyword="RouteSegmentLocationIDType"			Name="Route Segment Location ID Type"
(4010,1021) VERS="DICOS"	VR="CS"   VM="1-n"	Keyword="AbortReason"							Name="Abort Reason"
(4010,1023) VERS="DICOS"	VR="FL"   VM="1"	Keyword="VolumeOfPTO"							Name="Volume of PTO"
(4010,1024) VERS="DICOS"	VR="CS"   VM="1"	Keyword="AbortFlag"								Name="Abort Flag"
(4010,1025) VERS="DICOS"	VR="DT"   VM="1"	Keyword="RouteSegmentStartTime"					Name="Route Segment Start Time"
(4010,1026) VERS="DICOS"	VR="DT"   VM="1"	Keyword="RouteSegmentEndTime"					Name="Route Segment End Time"
(4010,1027) VERS="DICOS"	VR="CS"   VM="1"	Keyword="TDRType"								Name="TDR Type"
(4010,1028) VERS="DICOS"	VR="CS"   VM="1"	Keyword="InternationalRouteSegment"				Name="International Route Segment"
(4010,1029) VERS="DICOS"	VR="LO"   VM="1-n"	Keyword="ThreatDetectionAlgorithmandVersion"	Name="Threat Detection Algorithm and Version"
(4010,102A) VERS="DICOS"	VR="SH"   VM="1"	Keyword="AssignedLocation"						Name="Assigned Location"
(4010,102B) VERS="DICOS"	VR="DT"   VM="1"	Keyword="AlarmDecisionTime"						Name="Alarm Decision Time"
(4010,1031) VERS="DICOS"	VR="CS"   VM="1"	Keyword="AlarmDecision"							Name="Alarm Decision"
(4010,1033) VERS="DICOS"	VR="US"   VM="1"	Keyword="NumberOfTotalObjects"					Name="Number of Total Objects"
(4010,1034) VERS="DICOS"	VR="US"   VM="1"	Keyword="NumberOfAlarmObjects"					Name="Number of Alarm Objects"
(4010,1037) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="PTORepresentationSequence"				Name="PTO Representation Sequence"
(4010,1038) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="ATDAssessmentSequence"					Name="ATD Assessment Sequence"
(4010,1039) VERS="DICOS"	VR="CS"   VM="1"	Keyword="TIPType"								Name="TIP Type"
(4010,103A) VERS="DICOS"	VR="CS"   VM="1"	Keyword="DICOSVersion"							Name="DICOS Version"
(4010,1041) VERS="DICOS"	VR="DT"   VM="1"	Keyword="OOIOwnerCreationTime"					Name="OOI Owner Creation Time"
(4010,1042) VERS="DICOS"	VR="CS"   VM="1"	Keyword="OOIType"								Name="OOI Type"
(4010,1043) VERS="DICOS"	VR="FL"   VM="3"	Keyword="OOISize"								Name="OOI Size"
(4010,1044) VERS="DICOS"	VR="CS"   VM="1"	Keyword="AcquisitionStatus"						Name="Acquisition Status"
(4010,1045) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="BasisMaterialsCodeSequence"			Name="Basis Materials Code Sequence"
(4010,1046) VERS="DICOS"	VR="CS"   VM="1"	Keyword="PhantomType"							Name="Phantom Type"
(4010,1047) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="OOIOwnerSequence"						Name="OOI Owner Sequence"
(4010,1048) VERS="DICOS"	VR="CS"   VM="1"	Keyword="ScanType"								Name="Scan Type"
(4010,1051) VERS="DICOS"	VR="LO"   VM="1"	Keyword="ItineraryID"							Name="Itinerary ID"
(4010,1052) VERS="DICOS"	VR="SH"   VM="1"	Keyword="ItineraryIDType"						Name="Itinerary ID Type"
(4010,1053) VERS="DICOS"	VR="LO"   VM="1"	Keyword="ItineraryIDAssigningAuthority"			Name="Itinerary ID Assigning Authority"
(4010,1054) VERS="DICOS"	VR="SH"   VM="1"	Keyword="RouteID"								Name="Route ID"
(4010,1055) VERS="DICOS"	VR="SH"   VM="1"	Keyword="RouteIDAssigningAuthority"				Name="Route ID Assigning Authority"
(4010,1056) VERS="DICOS"	VR="CS"   VM="1"	Keyword="InboundArrivalType"					Name="Inbound Arrival Type"
(4010,1058) VERS="DICOS"	VR="SH"   VM="1"	Keyword="CarrierID"								Name="Carrier ID"
(4010,1059) VERS="DICOS"	VR="CS"   VM="1"	Keyword="CarrierIDAssigningAuthority"			Name="Carrier ID Assigning Authority"
(4010,1060) VERS="DICOS"	VR="FL"   VM="3"	Keyword="SourceOrientation"						Name="Source Orientation"
(4010,1061) VERS="DICOS"	VR="FL"   VM="3"	Keyword="SourcePosition"						Name="Source Position"
(4010,1062) VERS="DICOS"	VR="FL"   VM="1"	Keyword="BeltHeight"							Name="Belt Height"
(4010,1064) VERS="DICOS"	VR="SQ"   VM="1"	Keyword="AlgorithmRoutingCodeSequence"			Name="Algorithm Routing Code Sequence"
(4010,1067) VERS="DICOS"	VR="CS"   VM="1"	Keyword="TransportClassification"				Name="Transport Classification"
(4010,1068) VERS="DICOS"	VR="LT"   VM="1"	Keyword="OOITypeDescriptor"						Name="OOI Type Descriptor"
(4010,1069) VERS="DICOS"	VR="FL"   VM="1"	Keyword="TotalProcessingTime"					Name="Total Processing Time"
(4010,106C) VERS="DICOS"	VR="OB"   VM="1"	Keyword="DetectorCalibrationData"				Name="Detector Calibration Data"
