(0011,0023) VERS="DICONDE"	VR="ST"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="CADFileFormat"										Name="CAD File Format"
(0011,0024) VERS="DICONDE"	VR="ST"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="ComponentReferenceSystem"							Name="Component Reference System"
(0011,0025) VERS="DICONDE"	VR="ST"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="ComponentManufacturingProcedure"					Name="Component Manufacturing Procedure"
(0011,0028) VERS="DICONDE"	VR="ST"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="ComponentManufacturer"								Name="Component Manufacturer"
(0011,0030) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="MaterialThickness"									Name="Material Thickness"
(0011,0032) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="MaterialPipeDiameter"								Name="Material Pipe Diameter"
(0011,0034) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="MaterialIsolationDiameter"							Name="Material Isolation Diameter"
(0011,0042) VERS="DICONDE"	VR="ST"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="MaterialGrade"										Name="Material Grade"
(0011,0044) VERS="DICONDE"	VR="ST"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="MaterialPropertiesFileID"							Name="Material Properties File ID"
(0011,0045) VERS="DICONDE"	VR="ST"   VM="1-n"	Owner="astm.org/diconde/iod/Component"	Keyword="MaterialPropertiesFileFormat"						Name="Material Properties File Format"
(0011,0046) VERS="DICONDE"	VR="LT"   VM="1"	Owner="astm.org/diconde/iod/Component"	Keyword="MaterialNotes"										Name="Material Notes"
(0011,0050) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/Component"	Keyword="ComponentShape"									Name="Component Shape"
(0011,0052) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/Component"	Keyword="CurvatureType"										Name="Curvature Type"
(0011,0054) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/Component"	Keyword="OuterDiameter"										Name="Outer Diameter"
(0011,0056) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/Component"	Keyword="InnerDiameter"										Name="Inner Diameter"

(0009,0020) VERS="DICONDE"	VR="DA"   VM="1"	Owner="astm.org/diconde/iod/ComponentStudy"	Keyword="ExpiryDate"										Name="Expiry Date"

(0009,0010) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/ComponentSeries"	Keyword="ActualEnvironmentalConditions"						Name="Actual Environmental Conditions"
(0009,0040) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/ComponentSeries"	Keyword="EnvironmentalConditions"							Name="Environmental Conditions"

(0021,0002) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="EvaluatorSequence"									Name="Evaluator Sequence"
(0021,0004) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="EvaluatorNumber"									Name="Evaluator Number"
(0021,0006) VERS="DICONDE"	VR="PN"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="EvaluatorName"										Name="Evaluator Name"
(0021,0008) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="EvaluationAttempt"									Name="Evaluation Attempt"
(0021,0012) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationSequence"								Name="Indication Sequence"
(0021,0014) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationNumber"									Name="Indication Number "
(0021,0016) VERS="DICONDE"	VR="SH"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationLabel"									Name="Indication Label"
(0021,0018) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationDescription"								Name="Indication Description"
(0021,001A) VERS="DICONDE"	VR="CS"   VM="1-n"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationType"									Name="Indication Type"
(0021,001C) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationDisposition"								Name="Indication Disposition"
(0021,001E) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationROISequence"								Name="Indication ROI Sequence"
(0021,0030) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="IndicationPhysicalPropertySequence"				Name="Indication Physical Property Sequence"
(0021,0032) VERS="DICONDE"	VR="SH"   VM="1"	Owner="astm.org/diconde/iod/NdeIndication"	Keyword="PropertyLabel"										Name="Property Label"

(0021,0002) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemNumberOfAxes"						Name="Coordinate System Number of Axes "
(0021,0004) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemAxesSequence"						Name="Coordinate System Axes Sequence"
(0021,0006) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemAxisDescription"					Name="Coordinate System Axis Description"
(0021,0008) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemDataSetMapping"					Name="Coordinate System Data Set Mapping"
(0021,000A) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemAxisNumber"						Name="Coordinate System Axis Number"
(0021,000C) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemAxisType"							Name="Coordinate System Axis Type"
(0021,000E) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemAxisUnits"							Name="Coordinate System Axis Units"
(0021,0010) VERS="DICONDE"	VR="OB"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemAxisValues"						Name="Coordinate System Axis Values"
(0021,0020) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemTransformSequence"					Name="Coordinate System Transform Sequence"
(0021,0022) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="TransformDescription"								Name="Transform Description"
(0021,0024) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="TransformNumberOfAxes"								Name="Transform Number of Axes"
(0021,0026) VERS="DICONDE"	VR="IS"   VM="1-n"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="TransformOrderOfAxes"								Name="Transform Order of Axes"
(0021,0028) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="TransformedAxisUnits"								Name="Transformed Axis Units"
(0021,002A) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemTransformRotationAndScaleMatrix"	Name="Coordinate System Transform Rotation and Scale Matrix"
(0021,002C) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/NDEGeometry"	Keyword="CoordinateSystemTransformTranslationMatrix"		Name="Coordinate System Transform Translation Matrix"

(0009,0011) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxDetector"			Keyword="InternalDetectorFrameTime"							Name="Internal Detector Frame Time"
(0009,0012) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxDetector"			Keyword="NumberOfFramesIntegrated"							Name="Number of Frames Integrated"
(0009,0020) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeDxDetector"			Keyword="DetectorTemperatureSequence"						Name="Detector Temperature Sequence"
(0009,0022) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxDetector"			Keyword="SensorName"										Name="Sensor Name"
(0009,0024) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxDetector"			Keyword="HorizontalOffsetOfSensor"							Name="Horizontal Offset of Sensor"
(0009,0026) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxDetector"			Keyword="VerticalOffsetOfSensor"							Name="Vertical Offset of Sensor"
(0009,0028) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxDetector"			Keyword="SensorTemperature"									Name="Sensor Temperature"
(0009,0040) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="DarkCurrentSequence"								Name="Dark Current Sequence"
(0009,0050) VERS="DICONDE"	VR="OW/OB" VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="DarkCurrentCounts"									Name="Dark Current Counts"
(0009,0060) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="GainCorrectionReferenceSequence"					Name="Gain Correction Reference Sequence"
(0009,0070) VERS="DICONDE"	VR="OW/OB" VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="AirCounts"											Name="Air Counts"
(0009,0071) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="KVUsedInGainCalibration"							Name="KV Used in Gain Calibration"
(0009,0072) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="MAUsedInGainCalibration"							Name="MA Used in Gain Calibration"
(0009,0073) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="NumberOfFramesUsedForIntegration"					Name="Number of Frames Used for Integration"
(0009,0074) VERS="DICONDE"	VR="LO"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="FilterMaterialUsedInGainCalibration"				Name="Filter Material Used in Gain Calibration"
(0009,0075) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="FilterThicknessUsedInGainCalibration"				Name="Filter Thickness Used in Gain Calibration"
(0009,0076) VERS="DICONDE"	VR="DA"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="DateOfGainCalibration"								Name="Date of Gain Calibration"
(0009,0077) VERS="DICONDE"	VR="TM"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="TimeOfGainCalibration"								Name="Time of Gain Calibration"
(0009,0080) VERS="DICONDE"	VR="OB"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="BadPixelImage"										Name="Bad Pixel Image"
(0009,0099) VERS="DICONDE"	VR="LT"   VM="1"	Owner="astm.org/diconde/iod/NdeDxCalibrationData"	Keyword="CalibrationNotes"									Name="Calibration Notes"

(0009,0002) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="PulserEquipmentSequence"							Name="Pulser Equipment Sequence"
(0009,0004) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="PulserType"										Name="Pulser Type"
(0009,0006) VERS="DICONDE"	VR="LT"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="PulserNotes"										Name="Pulser Notes"
(0009,0008) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="ReceiverEquipmentSequence"							Name="Receiver Equipment Sequence"
(0009,000A) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="AmplifierType"										Name="Amplifier Type"
(0009,000C) VERS="DICONDE"	VR="LT"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="ReceiverNotes"										Name="Receiver Notes"
(0009,000E) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="PreAmplifierEquipmentSequence"						Name="Pre-Amplifier Equipment Sequence"
(0009,000F) VERS="DICONDE"	VR="LT"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="PreAmplifierNotes"									Name="Pre-Amplifier Notes"
(0009,0010) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="TransmitTransducerSequence"						Name="Transmit Transducer Sequence"
(0009,0011) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="ReceiveTransducerSequence"							Name="Receive Transducer Sequence"
(0009,0012) VERS="DICONDE"	VR="US"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="NumberOfElements"									Name="Number of Elements"
(0009,0013) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="ElementShape"										Name="Element Shape"
(0009,0014) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="ElementDimensionA"									Name="Element Dimension A"
(0009,0015) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="ElementDimensionB"									Name="Element Dimension B"
(0009,0016) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="ElementPitch"										Name="Element Pitch"
(0009,0017) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="MeasuredBeamDimensionA"							Name="Measured Beam Dimension A"
(0009,0018) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="MeasuredBeamDimensionB"							Name="Measured Beam Dimension B"
(0009,0019) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="LocationOfMeasuredBeamDiameter"					Name="Location of Measured Beam Diameter"
(0009,001A) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="NominalFrequency"									Name="Nominal Frequency"
(0009,001B) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="MeasuredCenterFrequency"							Name="Measured Center Frequency"
(0009,001C) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipment"	Keyword="MeasuredBandwidth"									Name="Measured Bandwidth"

(0009,0020) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="PulserSettingsSequence"							Name="Pulser Settings Sequence"
(0009,0022) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="PulseWidth"										Name="Pulse Width"
(0009,0024) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ExcitationFrequency"								Name="Excitation Frequency"
(0009,0026) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ModulationType"									Name="Modulation Type"
(0009,0028) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="Damping"											Name="Damping"
(0009,0030) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ReceiverSettingsSequence"							Name="Receiver Settings Sequence"
(0009,0031) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="AcquiredSoundpathLength"							Name="Acquired Soundpath Length"
(0009,0032) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="AcquisitionCompressionType"						Name="Acquisition Compression Type"
(0009,0033) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="AcquisitionSampleSize"								Name="Acquisition Sample Size"
(0009,0034) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="RectifierSmoothing"								Name="Rectifier Smoothing"
(0009,0035) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="DACSequence"										Name="DAC Sequence"
(0009,0036) VERS="DICONDE"	VR="CS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="DACType"											Name="DAC Type"
(0009,0038) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="DACGainPoints"										Name="DAC Gain Points"
(0009,003A) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="DACTimePoints"										Name="DAC Time Points"
(0009,003C) VERS="DICONDE"	VR="DS"   VM="1-n"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="DACAmplitude"										Name="DAC Amplitude"
(0009,0040) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="PreAmplifierSettingsSequence"						Name="Pre-Amplifier Settings Sequence"
(0009,0050) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="TransmitTransducerSettingsSequence"				Name="Transmit Transducer Settings Sequence"
(0009,0051) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ReceiveTransducerSettingsSequence"					Name="Receive Transducer Settings Sequence"
(0009,0052) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="IncidentAngle"										Name="Incident Angle"
(0009,0054) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CouplingTechnique"									Name="Coupling Technique"
(0009,0056) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CouplingMedium"									Name="Coupling Medium"
(0009,0057) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CouplingVelocity"									Name="Coupling Velocity"
(0009,0058) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CrystalCenterLocationX"							Name="Crystal Center Location X"
(0009,0059) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CrystalCenterLocationZ"							Name="Crystal Center Location Z"
(0009,005A) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="SoundPathLength"									Name="Sound Path Length"
(0009,005C) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="DelayLawIdentifier"								Name="Delay Law Identifier"
(0009,0060) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="GateSettingsSequence"								Name="Gate Settings Sequence"
(0009,0062) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="GateThreshold"										Name="Gate Threshold"
(0009,0064) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="VelocityOfSound"									Name="Velocity of Sound"
(0009,0070) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CalibrationSettingsSequence"						Name="Calibration Settings Sequence"
(0009,0072) VERS="DICONDE"	VR="ST"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CalibrationProcedure"								Name="Calibration Procedure"
(0009,0074) VERS="DICONDE"	VR="SH"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ProcedureVersion"									Name="Procedure Version"
(0009,0076) VERS="DICONDE"	VR="DA"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ProcedureCreationDate"								Name="Procedure Creation Date"
(0009,0078) VERS="DICONDE"	VR="DA"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ProcedureExpirationDate"							Name="Procedure Expiration Date"
(0009,007A) VERS="DICONDE"	VR="DA"   VM="1"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="ProcedureLastModifiedDate"							Name="Procedure Last Modified Date"
(0009,007C) VERS="DICONDE"	VR="TM"   VM="1-n"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CalibrationTime"									Name="Calibration Time"
(0009,007E) VERS="DICONDE"	VR="DA"   VM="1-n"	Owner="astm.org/diconde/iod/NdeUsEquipmentSettings"	Keyword="CalibrationDate"									Name="Calibration Date"

(0009,0002) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtImage"				Keyword="LINACEnergy"										Name="LINAC Energy"
(0009,0004) VERS="DICONDE"	VR="IS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtImage"				Keyword="LINACOutput"										Name="LINAC Output"
(0009,0011) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtDetector"			Keyword="InternalDetectorFrameTime"							Name="Internal Detector Frame Time"
(0009,0012) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtDetector"			Keyword="NumberOfFramesIntegrated"							Name="Number of Frames Integrated"
(0009,0020) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeCtDetector"			Keyword="DetectorTemperatureSequence"						Name="Detector Temperature Sequence"
(0009,0022) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtDetector"			Keyword="SensorName"										Name="Sensor Name"
(0009,0024) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtDetector"			Keyword="HorizontalOffsetOfSensor"							Name="Horizontal Offset of Sensor"
(0009,0026) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtDetector"			Keyword="VerticalOffsetOfSensor"							Name="Vertical Offset of Sensor"
(0009,0028) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtDetector"			Keyword="SensorTemperature"									Name="Sensor Temperature"
(0009,0040) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="DarkCurrentSequence"								Name="Dark Current Sequence"
(0009,0050) VERS="DICONDE"	VR="OW/OB" VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="DarkCurrentCounts"									Name="Dark Current Counts"
(0009,0060) VERS="DICONDE"	VR="SQ"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="GainCorrectionReferenceSequence"					Name="Gain Correction Reference Sequence"
(0009,0070) VERS="DICONDE"	VR="OW/OB" VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="AirCounts"											Name="Air Counts"
(0009,0071) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="KVUsedInGainCalibration"							Name="KV Used in Gain Calibration"
(0009,0072) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="MAUsedInGainCalibration"							Name="MA Used in Gain Calibration"
(0009,0073) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="NumberOfFramesUsedForIntegration"					Name="Number of Frames Used for Integration"
(0009,0074) VERS="DICONDE"	VR="LO"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="FilterMaterialUsedInGainCalibration"				Name="Filter Material Used in Gain Calibration"
(0009,0075) VERS="DICONDE"	VR="DS"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="FilterThicknessUsedInGainCalibration"				Name="Filter Thickness Used in Gain Calibration"
(0009,0076) VERS="DICONDE"	VR="DA"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="DateOfGainCalibration"								Name="Date of Gain Calibration"
(0009,0077) VERS="DICONDE"	VR="TM"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="TimeOfGainCalibration"								Name="Time of Gain Calibration"
(0009,0080) VERS="DICONDE"	VR="OB"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="BadPixelImage"										Name="Bad Pixel Image"
(0009,0099) VERS="DICONDE"	VR="LT"   VM="1"	Owner="astm.org/diconde/iod/NdeCtCalibrationData"	Keyword="CalibrationNotes"									Name="Calibration Notes"

