.TH DCINFLATE 1 "17 Dec 2000" "DICOM PS3" "DICOM PS3 - Decompress deflated DICOM file"
.SH NAME
dcinflate \- ACR/NEMA DICOM PS3 ... DICOM PS3 - Decompress deflated DICOM file
.SH SYNOPSIS
.HP 10
.B dcinflate "infile" "outfile"
.SH DESCRIPTION
.LP
.B dcinflate
reads the named dicom or acr-nema input file that is compressed using the deflate
transfer syntax, and copies the information and pixel data to a new dicom file,
in the explicit VR little endian uncompressed transfer syntax with a meta information
header prepended.
.SH OPTIONS
The verbose output goes to standard error.
.LP
There are no options.
.SH ENVIRONMENT
.LP
\ 
.SH EXAMPLES
.LP
\ 
.SH FILES
.LP
\ 
.SH SEE ALSO
.BR dcdeflate(1)
.SH AUTHOR
Copyright (C) 1993-2010. David A. Clunie DBA PixelMed Publishing. All rights reserved.
.SH BUGS
