.TH dcunbzip2 1 "23 Feb 2003" "DICOM PS3" "DICOM PS3 - Decompress deflated DICOM file"
.SH NAME
dcunbzip2 \- ACR/NEMA DICOM PS3 ... DICOM PS3 - Decompress deflated DICOM file
.SH SYNOPSIS
.HP 10
.B dcunbzip2 "infile" "outfile"
.SH DESCRIPTION
.LP
.B dcunbzip2
reads the named dicom or acr-nema input file that is compressed using the bzip2
transfer syntax, and copies the information and pixel data to a new dicom file,
in the explicit VR little endian uncompressed transfer syntax with a meta information
header prepended.
.SH OPTIONS
The verbose output goes to standard error.
.LP
There are no options.
.SH ENVIRONMENT
.LP
\ 
.SH EXAMPLES
.LP
\ 
.SH FILES
.LP
\ 
.SH SEE ALSO
.BR dcbzip2(1)
.SH AUTHOR
Copyright (C) 1993-2010. David A. Clunie DBA PixelMed Publishing. All rights reserved.
.SH BUGS
